version: '3.2'

networks:
  frontend:
    external:
      name: frontend

services:
  traefik:
    image: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=docker.fun"
      - "--docker.watch"
      - "--logLevel=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "2"
    deploy:
      labels:
        - "traefik.backend=traefik"
        - "traefik.port=8080"
        - "traefik.docker.network=frontend"
        - "traefik.frontend.rule=Host:traefik.docker.fun"
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  startpage:
    image: pierrezemb/gostatic
    volumes:
      - ./config/startpage:/srv/http
    networks:
      - frontend
    deploy:
      labels:
        - "traefik.backend=startpage"
        - "traefik.port=8043"
        - "traefik.docker.network=frontend"
        - "traefik.frontend.rule=Host:docker.fun"
