{
 "title": "OpenFaaS Serverless Dashboard",
 "description": "A Dashboard for the OpenFaaS serverless framework",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "function", "label": "function", "query": "label_values(function_name)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "content": "\n\n![](https://www.openfaas.com/assets/images/logo.png)"
  },
  {
   "title": "Gateway Health",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job=\"gateway\"}"
    }
   ]
  },
  {
   "title": "Gateway Service Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(gateway_service_count)" }
   ]
  },
  {
   "title": "Total Invocation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gateway_function_invocation_total)"
    }
   ]
  },
  {
   "title": "Replica scaling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gateway_service_count", "legendFormat": "{{function_name}} " }
   ]
  },
  {
   "title": "Execution duration (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(gateway_functions_seconds_sum[20s]) / rate(gateway_functions_seconds_count[20s]))",
     "legendFormat": "{{function_name}} "
    }
   ]
  },
  {
   "title": "Function rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (gateway_function_invocation_total [20s])",
     "legendFormat": "{{function_name}} {{code}}"
    }
   ]
  },
  {
   "title": "Duration Execution Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(rate(gateway_functions_seconds_sum[20s]) / rate(gateway_functions_seconds_count[20s]))",
     "legendFormat": "{{function_name}} "
    }
   ]
  }
 ]
}