# config file version
apiVersion: 1

# list of datasources to insert/update depending
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
  editable: true
  jsonData:
    scrapeInterval: 5s
